In [1]:
# creating spark session
exec(open('/home/jovyan/.ipython/profile_default/startup/00-spark-session.py').read())

Spark 3.5.0 session ready as `spark` (Delta Lake enabled).

In [2]:
# Adding Display functionality of Databricks 
exec(open('/home/jovyan/.ipython/profile_default/startup/01-databricks-utils.py').read())

Databricks-style helpers ready: display(), dbutils.fs/widgets/notebook, %run_notebook

In [12]:
from pyspark.sql.functions import *

In [10]:
df = spark.read.csv("/home/jovyan/data/Sample - Superstore.csv", header=True, inferSchema=False)

In [11]:
display(df)

In [14]:
new_df = df.withColumn("ingestion_time",(current_timestamp()))

In [15]:
new_df = new_df.withColumn("pk_id", sha2(concat_ws("||", *df.columns), 256))

In [16]:
display(new_df)

In [22]:
new_df.write \
    .mode("overwrite") \
    .option("header", "true") \
    .format("csv") \
    .save("/home/jovyan/data/superstore")